x=c(11,10,12,13,5)
cat("vector:","\n\n")
print(x)
a=matrix(data =c(1:12),nrow=3,ncol = 4)
cat("matrix:","\n\n")
print(a)
b=array(data = c(1:12),dim=c(3,4,2))
cat("array","\n\n")
print(b)
empid=c(10,11,12,13)
empName=c("sunil","akash","suhas","shivu")
empAge=c(25,20,23,22)
empList=list(empid,empName,empAge)
cat("emplist","\n\n")
print(empList)
df=data.frame(empid,empName,empAge)
cat("dataframe:","\n\n")
print(df)
fact=factor(c("male","female","male","female"))
cat("factor","\n\n")
print(fact)